name: CI

on:
  push:
    branches: [ "main", "arch/**", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools" "patcher;v4"
          yes | sdkmanager --licenses

      - name: Build and run unit tests
        run: ./gradlew clean :domain:test :core:test :data:test :app:test --stacktrace --warning-mode all

      - name: Generate coverage (Kover)
        run: ./gradlew koverXmlReport koverHtmlReport --stacktrace --warning-mode all

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: unit-test-reports
            path: |
              **/build/reports/tests/**
              **/build/test-results/**

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-kover
          path: |
            build/reports/kover/xml/report.xml
            build/reports/kover/html
