name: CI

on:
  push:
    branches: [ "main", "arch/**", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"
          yes | sdkmanager --licenses

      - name: Build and run unit tests
        run: |
          ./gradlew :domain:test :core:test :data:testDebugUnitTest :app:testDebugUnitTest --stacktrace --warning-mode all

      - name: Generate coverage (Kover)
        run: ./gradlew koverXmlReport --stacktrace --warning-mode all

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: unit-test-reports
            path: |
              **/build/reports/tests/**
              **/build/test-results/**

      - name: JUnit Report Summary
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: |
            **/build/test-results/test/*.xml
            **/build/test-results/testDebugUnitTest/*.xml
            **/build/test-results/testReleaseUnitTest/*.xml
          require_tests: false

      - name: Upload coverage report (XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-kover-xml
          path: build/reports/kover/xml/report.xml
